version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: teracy/ubuntu:16.04-dind-17.07.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install sudo & curl
          command: |
            apt-get update
            apt-get install -y sudo
            rm -rf /var/lib/apt/lists/*
            apt-get install -y curl
      - run:
          name: Install Minikube
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.22.3/minikube-linux-amd64
            chmod +x minikube
            mv minikube /usr/local/bin/
      - run:
          name: Install Kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.8.1/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Run Minikube
          command: |
            minikube start --vm-driver=none --extra-config=apiserver.InsecureServingOptions.BindAddress="127.0.0.1" --extra-config=apiserver.InsecureServingOptions.BindPort="8080"
      - run: kubectl version

